/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.platform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * The Atlassian provided system rules available.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-04T17:36:18.838627-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class AvailableWorkflowSystemRule {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_INCOMPATIBLE_RULE_KEYS = "incompatibleRuleKeys";
  @SerializedName(SERIALIZED_NAME_INCOMPATIBLE_RULE_KEYS)
  @javax.annotation.Nonnull
  private List<String> incompatibleRuleKeys = new ArrayList<>();

  public static final String SERIALIZED_NAME_IS_AVAILABLE_FOR_INITIAL_TRANSITION = "isAvailableForInitialTransition";
  @SerializedName(SERIALIZED_NAME_IS_AVAILABLE_FOR_INITIAL_TRANSITION)
  @javax.annotation.Nonnull
  private Boolean isAvailableForInitialTransition;

  public static final String SERIALIZED_NAME_IS_VISIBLE = "isVisible";
  @SerializedName(SERIALIZED_NAME_IS_VISIBLE)
  @javax.annotation.Nonnull
  private Boolean isVisible;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_RULE_KEY = "ruleKey";
  @SerializedName(SERIALIZED_NAME_RULE_KEY)
  @javax.annotation.Nonnull
  private String ruleKey;

  /**
   * The rule type.
   */
  @JsonAdapter(RuleTypeEnum.Adapter.class)
  public enum RuleTypeEnum {
    CONDITION("Condition"),
    
    VALIDATOR("Validator"),
    
    FUNCTION("Function"),
    
    SCREEN("Screen");

    private String value;

    RuleTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RuleTypeEnum fromValue(String value) {
      for (RuleTypeEnum b : RuleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RuleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RuleTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RuleTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RuleTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RuleTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RULE_TYPE = "ruleType";
  @SerializedName(SERIALIZED_NAME_RULE_TYPE)
  @javax.annotation.Nonnull
  private RuleTypeEnum ruleType;

  public AvailableWorkflowSystemRule() {
  }

  public AvailableWorkflowSystemRule description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * The rule description.
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public AvailableWorkflowSystemRule incompatibleRuleKeys(@javax.annotation.Nonnull List<String> incompatibleRuleKeys) {
    this.incompatibleRuleKeys = incompatibleRuleKeys;
    return this;
  }

  public AvailableWorkflowSystemRule addIncompatibleRuleKeysItem(String incompatibleRuleKeysItem) {
    if (this.incompatibleRuleKeys == null) {
      this.incompatibleRuleKeys = new ArrayList<>();
    }
    this.incompatibleRuleKeys.add(incompatibleRuleKeysItem);
    return this;
  }

  /**
   * List of rules that conflict with this one.
   * @return incompatibleRuleKeys
   */
  @javax.annotation.Nonnull
  public List<String> getIncompatibleRuleKeys() {
    return incompatibleRuleKeys;
  }

  public void setIncompatibleRuleKeys(@javax.annotation.Nonnull List<String> incompatibleRuleKeys) {
    this.incompatibleRuleKeys = incompatibleRuleKeys;
  }


  public AvailableWorkflowSystemRule isAvailableForInitialTransition(@javax.annotation.Nonnull Boolean isAvailableForInitialTransition) {
    this.isAvailableForInitialTransition = isAvailableForInitialTransition;
    return this;
  }

  /**
   * Whether the rule can be added added to an initial transition.
   * @return isAvailableForInitialTransition
   */
  @javax.annotation.Nonnull
  public Boolean getIsAvailableForInitialTransition() {
    return isAvailableForInitialTransition;
  }

  public void setIsAvailableForInitialTransition(@javax.annotation.Nonnull Boolean isAvailableForInitialTransition) {
    this.isAvailableForInitialTransition = isAvailableForInitialTransition;
  }


  public AvailableWorkflowSystemRule isVisible(@javax.annotation.Nonnull Boolean isVisible) {
    this.isVisible = isVisible;
    return this;
  }

  /**
   * Whether the rule is visible.
   * @return isVisible
   */
  @javax.annotation.Nonnull
  public Boolean getIsVisible() {
    return isVisible;
  }

  public void setIsVisible(@javax.annotation.Nonnull Boolean isVisible) {
    this.isVisible = isVisible;
  }


  public AvailableWorkflowSystemRule name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The rule name.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AvailableWorkflowSystemRule ruleKey(@javax.annotation.Nonnull String ruleKey) {
    this.ruleKey = ruleKey;
    return this;
  }

  /**
   * The rule key.
   * @return ruleKey
   */
  @javax.annotation.Nonnull
  public String getRuleKey() {
    return ruleKey;
  }

  public void setRuleKey(@javax.annotation.Nonnull String ruleKey) {
    this.ruleKey = ruleKey;
  }


  public AvailableWorkflowSystemRule ruleType(@javax.annotation.Nonnull RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
    return this;
  }

  /**
   * The rule type.
   * @return ruleType
   */
  @javax.annotation.Nonnull
  public RuleTypeEnum getRuleType() {
    return ruleType;
  }

  public void setRuleType(@javax.annotation.Nonnull RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableWorkflowSystemRule availableWorkflowSystemRule = (AvailableWorkflowSystemRule) o;
    return Objects.equals(this.description, availableWorkflowSystemRule.description) &&
        Objects.equals(this.incompatibleRuleKeys, availableWorkflowSystemRule.incompatibleRuleKeys) &&
        Objects.equals(this.isAvailableForInitialTransition, availableWorkflowSystemRule.isAvailableForInitialTransition) &&
        Objects.equals(this.isVisible, availableWorkflowSystemRule.isVisible) &&
        Objects.equals(this.name, availableWorkflowSystemRule.name) &&
        Objects.equals(this.ruleKey, availableWorkflowSystemRule.ruleKey) &&
        Objects.equals(this.ruleType, availableWorkflowSystemRule.ruleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, incompatibleRuleKeys, isAvailableForInitialTransition, isVisible, name, ruleKey, ruleType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableWorkflowSystemRule {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    incompatibleRuleKeys: ").append(toIndentedString(incompatibleRuleKeys)).append("\n");
    sb.append("    isAvailableForInitialTransition: ").append(toIndentedString(isAvailableForInitialTransition)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ruleKey: ").append(toIndentedString(ruleKey)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("incompatibleRuleKeys");
    openapiFields.add("isAvailableForInitialTransition");
    openapiFields.add("isVisible");
    openapiFields.add("name");
    openapiFields.add("ruleKey");
    openapiFields.add("ruleType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("description");
    openapiRequiredFields.add("incompatibleRuleKeys");
    openapiRequiredFields.add("isAvailableForInitialTransition");
    openapiRequiredFields.add("isVisible");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("ruleKey");
    openapiRequiredFields.add("ruleType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AvailableWorkflowSystemRule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AvailableWorkflowSystemRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AvailableWorkflowSystemRule is not found in the empty JSON string", AvailableWorkflowSystemRule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AvailableWorkflowSystemRule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AvailableWorkflowSystemRule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AvailableWorkflowSystemRule.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("incompatibleRuleKeys") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("incompatibleRuleKeys").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `incompatibleRuleKeys` to be an array in the JSON string but got `%s`", jsonObj.get("incompatibleRuleKeys").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("ruleKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ruleKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ruleKey").toString()));
      }
      if (!jsonObj.get("ruleType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ruleType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ruleType").toString()));
      }
      // validate the required field `ruleType`
      RuleTypeEnum.validateJsonElement(jsonObj.get("ruleType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AvailableWorkflowSystemRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AvailableWorkflowSystemRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AvailableWorkflowSystemRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AvailableWorkflowSystemRule.class));

       return (TypeAdapter<T>) new TypeAdapter<AvailableWorkflowSystemRule>() {
           @Override
           public void write(JsonWriter out, AvailableWorkflowSystemRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AvailableWorkflowSystemRule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AvailableWorkflowSystemRule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AvailableWorkflowSystemRule
   * @throws IOException if the JSON string is invalid with respect to AvailableWorkflowSystemRule
   */
  public static AvailableWorkflowSystemRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AvailableWorkflowSystemRule.class);
  }

  /**
   * Convert an instance of AvailableWorkflowSystemRule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

