/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.platform.model;

import java.util.Objects;
import com.atlassian.jira.platform.model.IssueBean;
import com.atlassian.jira.platform.model.IssueError;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * The list of requested issues &amp; fields.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-04T17:36:18.838627-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class BulkIssueResults {
  public static final String SERIALIZED_NAME_ISSUE_ERRORS = "issueErrors";
  @SerializedName(SERIALIZED_NAME_ISSUE_ERRORS)
  @javax.annotation.Nullable
  private List<IssueError> issueErrors = new ArrayList<>();

  public static final String SERIALIZED_NAME_ISSUES = "issues";
  @SerializedName(SERIALIZED_NAME_ISSUES)
  @javax.annotation.Nullable
  private List<IssueBean> issues = new ArrayList<>();

  public BulkIssueResults() {
  }

  public BulkIssueResults(
     List<IssueError> issueErrors, 
     List<IssueBean> issues
  ) {
    this();
    this.issueErrors = issueErrors;
    this.issues = issues;
  }

  /**
   * When Jira can&#39;t return an issue enumerated in a request due to a retriable error or payload constraint, we&#39;ll return the respective issue ID with a corresponding error message. This list is empty when there are no errors Issues which aren&#39;t found or that the user doesn&#39;t have permission to view won&#39;t be returned in this list.
   * @return issueErrors
   */
  @javax.annotation.Nullable
  public List<IssueError> getIssueErrors() {
    return issueErrors;
  }



  /**
   * The list of issues.
   * @return issues
   */
  @javax.annotation.Nullable
  public List<IssueBean> getIssues() {
    return issues;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkIssueResults bulkIssueResults = (BulkIssueResults) o;
    return Objects.equals(this.issueErrors, bulkIssueResults.issueErrors) &&
        Objects.equals(this.issues, bulkIssueResults.issues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueErrors, issues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkIssueResults {\n");
    sb.append("    issueErrors: ").append(toIndentedString(issueErrors)).append("\n");
    sb.append("    issues: ").append(toIndentedString(issues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("issueErrors");
    openapiFields.add("issues");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BulkIssueResults
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkIssueResults.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BulkIssueResults is not found in the empty JSON string", BulkIssueResults.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkIssueResults.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BulkIssueResults` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("issueErrors") != null && !jsonObj.get("issueErrors").isJsonNull()) {
        JsonArray jsonArrayissueErrors = jsonObj.getAsJsonArray("issueErrors");
        if (jsonArrayissueErrors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("issueErrors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `issueErrors` to be an array in the JSON string but got `%s`", jsonObj.get("issueErrors").toString()));
          }

          // validate the optional field `issueErrors` (array)
          for (int i = 0; i < jsonArrayissueErrors.size(); i++) {
            IssueError.validateJsonElement(jsonArrayissueErrors.get(i));
          };
        }
      }
      if (jsonObj.get("issues") != null && !jsonObj.get("issues").isJsonNull()) {
        JsonArray jsonArrayissues = jsonObj.getAsJsonArray("issues");
        if (jsonArrayissues != null) {
          // ensure the json data is an array
          if (!jsonObj.get("issues").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `issues` to be an array in the JSON string but got `%s`", jsonObj.get("issues").toString()));
          }

          // validate the optional field `issues` (array)
          for (int i = 0; i < jsonArrayissues.size(); i++) {
            IssueBean.validateJsonElement(jsonArrayissues.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkIssueResults.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkIssueResults' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkIssueResults> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkIssueResults.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkIssueResults>() {
           @Override
           public void write(JsonWriter out, BulkIssueResults value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkIssueResults read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BulkIssueResults given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BulkIssueResults
   * @throws IOException if the JSON string is invalid with respect to BulkIssueResults
   */
  public static BulkIssueResults fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkIssueResults.class);
  }

  /**
   * Convert an instance of BulkIssueResults to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

