/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.platform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * Details of the contextual configuration for a custom field.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-04T17:36:18.838627-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class BulkContextualConfiguration {
  public static final String SERIALIZED_NAME_CONFIGURATION = "configuration";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION)
  @javax.annotation.Nullable
  private Object _configuration = null;

  public static final String SERIALIZED_NAME_CUSTOM_FIELD_ID = "customFieldId";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELD_ID)
  @javax.annotation.Nonnull
  private String customFieldId;

  public static final String SERIALIZED_NAME_FIELD_CONTEXT_ID = "fieldContextId";
  @SerializedName(SERIALIZED_NAME_FIELD_CONTEXT_ID)
  @javax.annotation.Nonnull
  private String fieldContextId;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_SCHEMA = "schema";
  @SerializedName(SERIALIZED_NAME_SCHEMA)
  @javax.annotation.Nullable
  private Object schema = null;

  public BulkContextualConfiguration() {
  }

  public BulkContextualConfiguration(
     String fieldContextId
  ) {
    this();
    this.fieldContextId = fieldContextId;
  }

  public BulkContextualConfiguration _configuration(@javax.annotation.Nullable Object _configuration) {
    this._configuration = _configuration;
    return this;
  }

  /**
   * The field configuration.
   * @return _configuration
   */
  @javax.annotation.Nullable
  public Object getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(@javax.annotation.Nullable Object _configuration) {
    this._configuration = _configuration;
  }


  public BulkContextualConfiguration customFieldId(@javax.annotation.Nonnull String customFieldId) {
    this.customFieldId = customFieldId;
    return this;
  }

  /**
   * The ID of the custom field.
   * @return customFieldId
   */
  @javax.annotation.Nonnull
  public String getCustomFieldId() {
    return customFieldId;
  }

  public void setCustomFieldId(@javax.annotation.Nonnull String customFieldId) {
    this.customFieldId = customFieldId;
  }


  /**
   * The ID of the field context the configuration is associated with.
   * @return fieldContextId
   */
  @javax.annotation.Nonnull
  public String getFieldContextId() {
    return fieldContextId;
  }



  public BulkContextualConfiguration id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the configuration.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public BulkContextualConfiguration schema(@javax.annotation.Nullable Object schema) {
    this.schema = schema;
    return this;
  }

  /**
   * The field value schema.
   * @return schema
   */
  @javax.annotation.Nullable
  public Object getSchema() {
    return schema;
  }

  public void setSchema(@javax.annotation.Nullable Object schema) {
    this.schema = schema;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkContextualConfiguration bulkContextualConfiguration = (BulkContextualConfiguration) o;
    return Objects.equals(this._configuration, bulkContextualConfiguration._configuration) &&
        Objects.equals(this.customFieldId, bulkContextualConfiguration.customFieldId) &&
        Objects.equals(this.fieldContextId, bulkContextualConfiguration.fieldContextId) &&
        Objects.equals(this.id, bulkContextualConfiguration.id) &&
        Objects.equals(this.schema, bulkContextualConfiguration.schema);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(_configuration, customFieldId, fieldContextId, id, schema);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkContextualConfiguration {\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    customFieldId: ").append(toIndentedString(customFieldId)).append("\n");
    sb.append("    fieldContextId: ").append(toIndentedString(fieldContextId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("configuration");
    openapiFields.add("customFieldId");
    openapiFields.add("fieldContextId");
    openapiFields.add("id");
    openapiFields.add("schema");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("customFieldId");
    openapiRequiredFields.add("fieldContextId");
    openapiRequiredFields.add("id");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BulkContextualConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkContextualConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BulkContextualConfiguration is not found in the empty JSON string", BulkContextualConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkContextualConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BulkContextualConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BulkContextualConfiguration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("customFieldId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customFieldId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customFieldId").toString()));
      }
      if (!jsonObj.get("fieldContextId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fieldContextId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fieldContextId").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkContextualConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkContextualConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkContextualConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkContextualConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkContextualConfiguration>() {
           @Override
           public void write(JsonWriter out, BulkContextualConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkContextualConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BulkContextualConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BulkContextualConfiguration
   * @throws IOException if the JSON string is invalid with respect to BulkContextualConfiguration
   */
  public static BulkContextualConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkContextualConfiguration.class);
  }

  /**
   * Convert an instance of BulkContextualConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

