/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-1461af1efd5cc75bf21cb8256a8b42f9bd4278be
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.platform.model;

import java.util.Objects;
import com.atlassian.jira.platform.model.WorkflowRuleConfiguration;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * The conditions group associated with the transition.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-04T17:36:18.838627-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class ConditionGroupUpdate {
  public static final String SERIALIZED_NAME_CONDITION_GROUPS = "conditionGroups";
  @SerializedName(SERIALIZED_NAME_CONDITION_GROUPS)
  @javax.annotation.Nullable
  private List<ConditionGroupUpdate> conditionGroups = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  @javax.annotation.Nullable
  private List<WorkflowRuleConfiguration> conditions = new ArrayList<>();

  /**
   * Determines how the conditions in the group are evaluated. Accepts either &#x60;ANY&#x60; or &#x60;ALL&#x60;. If &#x60;ANY&#x60; is used, at least one condition in the group must be true for the group to evaluate to true. If &#x60;ALL&#x60; is used, all conditions in the group must be true for the group to evaluate to true.
   */
  @JsonAdapter(OperationEnum.Adapter.class)
  public enum OperationEnum {
    ANY("ANY"),
    
    ALL("ALL");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperationEnum fromValue(String value) {
      for (OperationEnum b : OperationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OperationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperationEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OperationEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OperationEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  @javax.annotation.Nonnull
  private OperationEnum operation;

  public ConditionGroupUpdate() {
  }

  public ConditionGroupUpdate conditionGroups(@javax.annotation.Nullable List<ConditionGroupUpdate> conditionGroups) {
    this.conditionGroups = conditionGroups;
    return this;
  }

  public ConditionGroupUpdate addConditionGroupsItem(ConditionGroupUpdate conditionGroupsItem) {
    if (this.conditionGroups == null) {
      this.conditionGroups = new ArrayList<>();
    }
    this.conditionGroups.add(conditionGroupsItem);
    return this;
  }

  /**
   * The nested conditions of the condition group.
   * @return conditionGroups
   */
  @javax.annotation.Nullable
  public List<ConditionGroupUpdate> getConditionGroups() {
    return conditionGroups;
  }

  public void setConditionGroups(@javax.annotation.Nullable List<ConditionGroupUpdate> conditionGroups) {
    this.conditionGroups = conditionGroups;
  }


  public ConditionGroupUpdate conditions(@javax.annotation.Nullable List<WorkflowRuleConfiguration> conditions) {
    this.conditions = conditions;
    return this;
  }

  public ConditionGroupUpdate addConditionsItem(WorkflowRuleConfiguration conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

  /**
   * The rules for this condition.
   * @return conditions
   */
  @javax.annotation.Nullable
  public List<WorkflowRuleConfiguration> getConditions() {
    return conditions;
  }

  public void setConditions(@javax.annotation.Nullable List<WorkflowRuleConfiguration> conditions) {
    this.conditions = conditions;
  }


  public ConditionGroupUpdate operation(@javax.annotation.Nonnull OperationEnum operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Determines how the conditions in the group are evaluated. Accepts either &#x60;ANY&#x60; or &#x60;ALL&#x60;. If &#x60;ANY&#x60; is used, at least one condition in the group must be true for the group to evaluate to true. If &#x60;ALL&#x60; is used, all conditions in the group must be true for the group to evaluate to true.
   * @return operation
   */
  @javax.annotation.Nonnull
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(@javax.annotation.Nonnull OperationEnum operation) {
    this.operation = operation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionGroupUpdate conditionGroupUpdate = (ConditionGroupUpdate) o;
    return Objects.equals(this.conditionGroups, conditionGroupUpdate.conditionGroups) &&
        Objects.equals(this.conditions, conditionGroupUpdate.conditions) &&
        Objects.equals(this.operation, conditionGroupUpdate.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditionGroups, conditions, operation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionGroupUpdate {\n");
    sb.append("    conditionGroups: ").append(toIndentedString(conditionGroups)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("conditionGroups");
    openapiFields.add("conditions");
    openapiFields.add("operation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("operation");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConditionGroupUpdate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConditionGroupUpdate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConditionGroupUpdate is not found in the empty JSON string", ConditionGroupUpdate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConditionGroupUpdate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConditionGroupUpdate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConditionGroupUpdate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("conditionGroups") != null && !jsonObj.get("conditionGroups").isJsonNull()) {
        JsonArray jsonArrayconditionGroups = jsonObj.getAsJsonArray("conditionGroups");
        if (jsonArrayconditionGroups != null) {
          // ensure the json data is an array
          if (!jsonObj.get("conditionGroups").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `conditionGroups` to be an array in the JSON string but got `%s`", jsonObj.get("conditionGroups").toString()));
          }

          // validate the optional field `conditionGroups` (array)
          for (int i = 0; i < jsonArrayconditionGroups.size(); i++) {
            ConditionGroupUpdate.validateJsonElement(jsonArrayconditionGroups.get(i));
          };
        }
      }
      if (jsonObj.get("conditions") != null && !jsonObj.get("conditions").isJsonNull()) {
        JsonArray jsonArrayconditions = jsonObj.getAsJsonArray("conditions");
        if (jsonArrayconditions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("conditions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `conditions` to be an array in the JSON string but got `%s`", jsonObj.get("conditions").toString()));
          }

          // validate the optional field `conditions` (array)
          for (int i = 0; i < jsonArrayconditions.size(); i++) {
            WorkflowRuleConfiguration.validateJsonElement(jsonArrayconditions.get(i));
          };
        }
      }
      if (!jsonObj.get("operation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `operation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operation").toString()));
      }
      // validate the required field `operation`
      OperationEnum.validateJsonElement(jsonObj.get("operation"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConditionGroupUpdate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConditionGroupUpdate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConditionGroupUpdate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConditionGroupUpdate.class));

       return (TypeAdapter<T>) new TypeAdapter<ConditionGroupUpdate>() {
           @Override
           public void write(JsonWriter out, ConditionGroupUpdate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConditionGroupUpdate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConditionGroupUpdate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConditionGroupUpdate
   * @throws IOException if the JSON string is invalid with respect to ConditionGroupUpdate
   */
  public static ConditionGroupUpdate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConditionGroupUpdate.class);
  }

  /**
   * Convert an instance of ConditionGroupUpdate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

