/*
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.software.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * GetConfiguration200ResponseRanking
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-05T13:52:26.392070-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class GetConfiguration200ResponseRanking {
  public static final String SERIALIZED_NAME_RANK_CUSTOM_FIELD_ID = "rankCustomFieldId";
  @SerializedName(SERIALIZED_NAME_RANK_CUSTOM_FIELD_ID)
  @javax.annotation.Nullable
  private Long rankCustomFieldId;

  public GetConfiguration200ResponseRanking() {
  }

  public GetConfiguration200ResponseRanking rankCustomFieldId(@javax.annotation.Nullable Long rankCustomFieldId) {
    this.rankCustomFieldId = rankCustomFieldId;
    return this;
  }

  /**
   * Get rankCustomFieldId
   * @return rankCustomFieldId
   */
  @javax.annotation.Nullable
  public Long getRankCustomFieldId() {
    return rankCustomFieldId;
  }

  public void setRankCustomFieldId(@javax.annotation.Nullable Long rankCustomFieldId) {
    this.rankCustomFieldId = rankCustomFieldId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConfiguration200ResponseRanking getConfiguration200ResponseRanking = (GetConfiguration200ResponseRanking) o;
    return Objects.equals(this.rankCustomFieldId, getConfiguration200ResponseRanking.rankCustomFieldId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rankCustomFieldId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConfiguration200ResponseRanking {\n");
    sb.append("    rankCustomFieldId: ").append(toIndentedString(rankCustomFieldId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rankCustomFieldId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetConfiguration200ResponseRanking
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetConfiguration200ResponseRanking.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetConfiguration200ResponseRanking is not found in the empty JSON string", GetConfiguration200ResponseRanking.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetConfiguration200ResponseRanking.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetConfiguration200ResponseRanking` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetConfiguration200ResponseRanking.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetConfiguration200ResponseRanking' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetConfiguration200ResponseRanking> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetConfiguration200ResponseRanking.class));

       return (TypeAdapter<T>) new TypeAdapter<GetConfiguration200ResponseRanking>() {
           @Override
           public void write(JsonWriter out, GetConfiguration200ResponseRanking value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetConfiguration200ResponseRanking read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetConfiguration200ResponseRanking given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetConfiguration200ResponseRanking
   * @throws IOException if the JSON string is invalid with respect to GetConfiguration200ResponseRanking
   */
  public static GetConfiguration200ResponseRanking fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetConfiguration200ResponseRanking.class);
  }

  /**
   * Convert an instance of GetConfiguration200ResponseRanking to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

