/*
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.software.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * IssueBeanFieldsToInclude
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-05T13:52:26.392070-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class IssueBeanFieldsToInclude {
  public static final String SERIALIZED_NAME_ACTUALLY_INCLUDED = "actuallyIncluded";
  @SerializedName(SERIALIZED_NAME_ACTUALLY_INCLUDED)
  @javax.annotation.Nullable
  private Set<String> actuallyIncluded = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_EXCLUDED = "excluded";
  @SerializedName(SERIALIZED_NAME_EXCLUDED)
  @javax.annotation.Nullable
  private Set<String> excluded = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_INCLUDED = "included";
  @SerializedName(SERIALIZED_NAME_INCLUDED)
  @javax.annotation.Nullable
  private Set<String> included = new LinkedHashSet<>();

  public IssueBeanFieldsToInclude() {
  }

  public IssueBeanFieldsToInclude actuallyIncluded(@javax.annotation.Nullable Set<String> actuallyIncluded) {
    this.actuallyIncluded = actuallyIncluded;
    return this;
  }

  public IssueBeanFieldsToInclude addActuallyIncludedItem(String actuallyIncludedItem) {
    if (this.actuallyIncluded == null) {
      this.actuallyIncluded = new LinkedHashSet<>();
    }
    this.actuallyIncluded.add(actuallyIncludedItem);
    return this;
  }

  /**
   * Get actuallyIncluded
   * @return actuallyIncluded
   */
  @javax.annotation.Nullable
  public Set<String> getActuallyIncluded() {
    return actuallyIncluded;
  }

  public void setActuallyIncluded(@javax.annotation.Nullable Set<String> actuallyIncluded) {
    this.actuallyIncluded = actuallyIncluded;
  }


  public IssueBeanFieldsToInclude excluded(@javax.annotation.Nullable Set<String> excluded) {
    this.excluded = excluded;
    return this;
  }

  public IssueBeanFieldsToInclude addExcludedItem(String excludedItem) {
    if (this.excluded == null) {
      this.excluded = new LinkedHashSet<>();
    }
    this.excluded.add(excludedItem);
    return this;
  }

  /**
   * Get excluded
   * @return excluded
   */
  @javax.annotation.Nullable
  public Set<String> getExcluded() {
    return excluded;
  }

  public void setExcluded(@javax.annotation.Nullable Set<String> excluded) {
    this.excluded = excluded;
  }


  public IssueBeanFieldsToInclude included(@javax.annotation.Nullable Set<String> included) {
    this.included = included;
    return this;
  }

  public IssueBeanFieldsToInclude addIncludedItem(String includedItem) {
    if (this.included == null) {
      this.included = new LinkedHashSet<>();
    }
    this.included.add(includedItem);
    return this;
  }

  /**
   * Get included
   * @return included
   */
  @javax.annotation.Nullable
  public Set<String> getIncluded() {
    return included;
  }

  public void setIncluded(@javax.annotation.Nullable Set<String> included) {
    this.included = included;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueBeanFieldsToInclude issueBeanFieldsToInclude = (IssueBeanFieldsToInclude) o;
    return Objects.equals(this.actuallyIncluded, issueBeanFieldsToInclude.actuallyIncluded) &&
        Objects.equals(this.excluded, issueBeanFieldsToInclude.excluded) &&
        Objects.equals(this.included, issueBeanFieldsToInclude.included);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actuallyIncluded, excluded, included);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueBeanFieldsToInclude {\n");
    sb.append("    actuallyIncluded: ").append(toIndentedString(actuallyIncluded)).append("\n");
    sb.append("    excluded: ").append(toIndentedString(excluded)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actuallyIncluded");
    openapiFields.add("excluded");
    openapiFields.add("included");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IssueBeanFieldsToInclude
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IssueBeanFieldsToInclude.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IssueBeanFieldsToInclude is not found in the empty JSON string", IssueBeanFieldsToInclude.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IssueBeanFieldsToInclude.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IssueBeanFieldsToInclude` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("actuallyIncluded") != null && !jsonObj.get("actuallyIncluded").isJsonNull() && !jsonObj.get("actuallyIncluded").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `actuallyIncluded` to be an array in the JSON string but got `%s`", jsonObj.get("actuallyIncluded").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("excluded") != null && !jsonObj.get("excluded").isJsonNull() && !jsonObj.get("excluded").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `excluded` to be an array in the JSON string but got `%s`", jsonObj.get("excluded").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("included") != null && !jsonObj.get("included").isJsonNull() && !jsonObj.get("included").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `included` to be an array in the JSON string but got `%s`", jsonObj.get("included").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IssueBeanFieldsToInclude.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IssueBeanFieldsToInclude' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IssueBeanFieldsToInclude> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IssueBeanFieldsToInclude.class));

       return (TypeAdapter<T>) new TypeAdapter<IssueBeanFieldsToInclude>() {
           @Override
           public void write(JsonWriter out, IssueBeanFieldsToInclude value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IssueBeanFieldsToInclude read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IssueBeanFieldsToInclude given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IssueBeanFieldsToInclude
   * @throws IOException if the JSON string is invalid with respect to IssueBeanFieldsToInclude
   */
  public static IssueBeanFieldsToInclude fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IssueBeanFieldsToInclude.class);
  }

  /**
   * Convert an instance of IssueBeanFieldsToInclude to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

