/*
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.software.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * PartiallyUpdateSprint200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-05T13:52:26.392070-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class PartiallyUpdateSprint200Response {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  @javax.annotation.Nullable
  private String self;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private String state;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime endDate;

  public static final String SERIALIZED_NAME_COMPLETE_DATE = "completeDate";
  @SerializedName(SERIALIZED_NAME_COMPLETE_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime completeDate;

  public static final String SERIALIZED_NAME_ORIGIN_BOARD_ID = "originBoardId";
  @SerializedName(SERIALIZED_NAME_ORIGIN_BOARD_ID)
  @javax.annotation.Nullable
  private Integer originBoardId;

  public static final String SERIALIZED_NAME_GOAL = "goal";
  @SerializedName(SERIALIZED_NAME_GOAL)
  @javax.annotation.Nullable
  private String goal;

  public PartiallyUpdateSprint200Response() {
  }

  public PartiallyUpdateSprint200Response id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the sprint.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public PartiallyUpdateSprint200Response self(@javax.annotation.Nullable String self) {
    this.self = self;
    return this;
  }

  /**
   * The URL of the sprint.
   * @return self
   */
  @javax.annotation.Nullable
  public String getSelf() {
    return self;
  }

  public void setSelf(@javax.annotation.Nullable String self) {
    this.self = self;
  }


  public PartiallyUpdateSprint200Response state(@javax.annotation.Nullable String state) {
    this.state = state;
    return this;
  }

  /**
   * The current state of the sprint.
   * @return state
   */
  @javax.annotation.Nullable
  public String getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }


  public PartiallyUpdateSprint200Response name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the sprint.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public PartiallyUpdateSprint200Response startDate(@javax.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * The start date of the sprint.
   * @return startDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(@javax.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  public PartiallyUpdateSprint200Response endDate(@javax.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * The end date of the sprint.
   * @return endDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(@javax.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public PartiallyUpdateSprint200Response completeDate(@javax.annotation.Nullable OffsetDateTime completeDate) {
    this.completeDate = completeDate;
    return this;
  }

  /**
   * The date when the sprint was completed.
   * @return completeDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCompleteDate() {
    return completeDate;
  }

  public void setCompleteDate(@javax.annotation.Nullable OffsetDateTime completeDate) {
    this.completeDate = completeDate;
  }


  public PartiallyUpdateSprint200Response originBoardId(@javax.annotation.Nullable Integer originBoardId) {
    this.originBoardId = originBoardId;
    return this;
  }

  /**
   * The ID of the board the sprint belongs to.
   * @return originBoardId
   */
  @javax.annotation.Nullable
  public Integer getOriginBoardId() {
    return originBoardId;
  }

  public void setOriginBoardId(@javax.annotation.Nullable Integer originBoardId) {
    this.originBoardId = originBoardId;
  }


  public PartiallyUpdateSprint200Response goal(@javax.annotation.Nullable String goal) {
    this.goal = goal;
    return this;
  }

  /**
   * The goal of the sprint.
   * @return goal
   */
  @javax.annotation.Nullable
  public String getGoal() {
    return goal;
  }

  public void setGoal(@javax.annotation.Nullable String goal) {
    this.goal = goal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartiallyUpdateSprint200Response partiallyUpdateSprint200Response = (PartiallyUpdateSprint200Response) o;
    return Objects.equals(this.id, partiallyUpdateSprint200Response.id) &&
        Objects.equals(this.self, partiallyUpdateSprint200Response.self) &&
        Objects.equals(this.state, partiallyUpdateSprint200Response.state) &&
        Objects.equals(this.name, partiallyUpdateSprint200Response.name) &&
        Objects.equals(this.startDate, partiallyUpdateSprint200Response.startDate) &&
        Objects.equals(this.endDate, partiallyUpdateSprint200Response.endDate) &&
        Objects.equals(this.completeDate, partiallyUpdateSprint200Response.completeDate) &&
        Objects.equals(this.originBoardId, partiallyUpdateSprint200Response.originBoardId) &&
        Objects.equals(this.goal, partiallyUpdateSprint200Response.goal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, self, state, name, startDate, endDate, completeDate, originBoardId, goal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartiallyUpdateSprint200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    completeDate: ").append(toIndentedString(completeDate)).append("\n");
    sb.append("    originBoardId: ").append(toIndentedString(originBoardId)).append("\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("self");
    openapiFields.add("state");
    openapiFields.add("name");
    openapiFields.add("startDate");
    openapiFields.add("endDate");
    openapiFields.add("completeDate");
    openapiFields.add("originBoardId");
    openapiFields.add("goal");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PartiallyUpdateSprint200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PartiallyUpdateSprint200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PartiallyUpdateSprint200Response is not found in the empty JSON string", PartiallyUpdateSprint200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PartiallyUpdateSprint200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PartiallyUpdateSprint200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("self") != null && !jsonObj.get("self").isJsonNull()) && !jsonObj.get("self").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `self` to be a primitive type in the JSON string but got `%s`", jsonObj.get("self").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("goal") != null && !jsonObj.get("goal").isJsonNull()) && !jsonObj.get("goal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `goal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("goal").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PartiallyUpdateSprint200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PartiallyUpdateSprint200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PartiallyUpdateSprint200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PartiallyUpdateSprint200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<PartiallyUpdateSprint200Response>() {
           @Override
           public void write(JsonWriter out, PartiallyUpdateSprint200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PartiallyUpdateSprint200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PartiallyUpdateSprint200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PartiallyUpdateSprint200Response
   * @throws IOException if the JSON string is invalid with respect to PartiallyUpdateSprint200Response
   */
  public static PartiallyUpdateSprint200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PartiallyUpdateSprint200Response.class);
  }

  /**
   * Convert an instance of PartiallyUpdateSprint200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

