/*
 * Jira Software Cloud API
 * Jira Software Cloud REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.software.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.atlassian.jira.invoker.JSON;

/**
 * Information about tests that were executed during a build. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-05T13:52:26.392070-04:00[America/New_York]", comments = "Generator version: 7.12.0")
public class TestInfo {
  public static final String SERIALIZED_NAME_TOTAL_NUMBER = "totalNumber";
  @SerializedName(SERIALIZED_NAME_TOTAL_NUMBER)
  @javax.annotation.Nonnull
  private Long totalNumber;

  public static final String SERIALIZED_NAME_NUMBER_PASSED = "numberPassed";
  @SerializedName(SERIALIZED_NAME_NUMBER_PASSED)
  @javax.annotation.Nonnull
  private Long numberPassed;

  public static final String SERIALIZED_NAME_NUMBER_FAILED = "numberFailed";
  @SerializedName(SERIALIZED_NAME_NUMBER_FAILED)
  @javax.annotation.Nonnull
  private Long numberFailed;

  public static final String SERIALIZED_NAME_NUMBER_SKIPPED = "numberSkipped";
  @SerializedName(SERIALIZED_NAME_NUMBER_SKIPPED)
  @javax.annotation.Nullable
  private Long numberSkipped = 0l;

  public TestInfo() {
  }

  public TestInfo totalNumber(@javax.annotation.Nonnull Long totalNumber) {
    this.totalNumber = totalNumber;
    return this;
  }

  /**
   * The total number of tests considered during a build. 
   * @return totalNumber
   */
  @javax.annotation.Nonnull
  public Long getTotalNumber() {
    return totalNumber;
  }

  public void setTotalNumber(@javax.annotation.Nonnull Long totalNumber) {
    this.totalNumber = totalNumber;
  }


  public TestInfo numberPassed(@javax.annotation.Nonnull Long numberPassed) {
    this.numberPassed = numberPassed;
    return this;
  }

  /**
   * The number of tests that passed during a build. 
   * @return numberPassed
   */
  @javax.annotation.Nonnull
  public Long getNumberPassed() {
    return numberPassed;
  }

  public void setNumberPassed(@javax.annotation.Nonnull Long numberPassed) {
    this.numberPassed = numberPassed;
  }


  public TestInfo numberFailed(@javax.annotation.Nonnull Long numberFailed) {
    this.numberFailed = numberFailed;
    return this;
  }

  /**
   * The number of tests that failed during a build. 
   * @return numberFailed
   */
  @javax.annotation.Nonnull
  public Long getNumberFailed() {
    return numberFailed;
  }

  public void setNumberFailed(@javax.annotation.Nonnull Long numberFailed) {
    this.numberFailed = numberFailed;
  }


  public TestInfo numberSkipped(@javax.annotation.Nullable Long numberSkipped) {
    this.numberSkipped = numberSkipped;
    return this;
  }

  /**
   * The number of tests that were skipped during a build. 
   * @return numberSkipped
   */
  @javax.annotation.Nullable
  public Long getNumberSkipped() {
    return numberSkipped;
  }

  public void setNumberSkipped(@javax.annotation.Nullable Long numberSkipped) {
    this.numberSkipped = numberSkipped;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestInfo testInfo = (TestInfo) o;
    return Objects.equals(this.totalNumber, testInfo.totalNumber) &&
        Objects.equals(this.numberPassed, testInfo.numberPassed) &&
        Objects.equals(this.numberFailed, testInfo.numberFailed) &&
        Objects.equals(this.numberSkipped, testInfo.numberSkipped);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalNumber, numberPassed, numberFailed, numberSkipped);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestInfo {\n");
    sb.append("    totalNumber: ").append(toIndentedString(totalNumber)).append("\n");
    sb.append("    numberPassed: ").append(toIndentedString(numberPassed)).append("\n");
    sb.append("    numberFailed: ").append(toIndentedString(numberFailed)).append("\n");
    sb.append("    numberSkipped: ").append(toIndentedString(numberSkipped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("totalNumber");
    openapiFields.add("numberPassed");
    openapiFields.add("numberFailed");
    openapiFields.add("numberSkipped");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("totalNumber");
    openapiRequiredFields.add("numberPassed");
    openapiRequiredFields.add("numberFailed");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TestInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TestInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TestInfo is not found in the empty JSON string", TestInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TestInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TestInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TestInfo.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TestInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TestInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TestInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TestInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<TestInfo>() {
           @Override
           public void write(JsonWriter out, TestInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TestInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             //validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TestInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TestInfo
   * @throws IOException if the JSON string is invalid with respect to TestInfo
   */
  public static TestInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TestInfo.class);
  }

  /**
   * Convert an instance of TestInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

