name: Docker Publish

on:
  push:
    tags: [ 'v*' ]

env:
  IMAGE_NAME: jira-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Permission to publish packages
      contents: write # For creating releases and uploading assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw package

      - name: Process tag name
        id: tag
        run: |
          # Remove 'v' prefix from tag name
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT
          
          # Check if tag is standard semantic version (digits and dots only)
          if [[ $TAG_NAME =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image (with latest tag)
        if: steps.tag.outputs.IS_RELEASE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Build and push Docker image (without latest tag)
        if: steps.tag.outputs.IS_RELEASE == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG_NAME }}