name: Docker Publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Permission to publish packages
      contents: write # For creating releases and uploading assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw package

      - name: Process tag name
        id: tag
        run: |
          # Remove 'v' prefix from tag name
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jdbc-mcp:${{ steps.tag.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/jdbc-mcp:latest
